name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [v2.x]

    steps:
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history and tags
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: deno fmt --check
      - run: deno lint
      - name: Test
        run: |
          git fetch origin # some branches are necessary for testing
          deno task coverage
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
